### ISSUE TITLE
Angular 2 full release

### ISSUE THREAD

**Issue by SamuelMarks** [FountainJS/generator-fountain-angular2#87] opened 2016-09-18 01:19 UTC
FYI: http://angularjs.blogspot.com.au/2016/09/angular2-final.html

:1234:

**Comment by Swiip** [comment] 2016-09-23 06:28
Duplicate of https://github.com/FountainJS/generator-fountain-webapp/issues/131 PR in progress.

**Closed** 2016-09-23 09:25 UTC
Labels: fixed-in-next-release
